### ISSUE TITLE
f*(t) is not correspond with paper

### ISSUE THREAD

**Issue by destinyyzy** [musically-ut/tf_rmtpp#4]
line 247 of tf_rmtpp/src/tf_rmtpp/rmtpp_core.py.
the sign may be wrong.

**Comment by musically-ut** [comment]
Thanks for the report; I will check up on it once I get access to a proper workstation. In the meanwhile, could you suggest what it should have been? Perhaps via a PR?

Thanks!

**Comment by musically-ut** [comment]
Your observation in the PR that the equations in the code do not match the paper are correct, but only because in the code, I've added a `tf.nn.softplus` operator on `wt` to make it positive. Then I have had to change its sign for the remaining equations. Hence, if you replace `wt` with `-wt` in the original paper, you will recover the original equations.

Please reopen the issue/PR if you think that there still is a problem.

Thanks!
